format = "$directory$character"
right_format = "$git_branch$python$aws"
add_newline = false

[line_break]
disabled = true

[aws]
format = "on [$symbol($profile)]($style)"

[python]
format = "on [$symbol($virtualenv)]($style)"
