theme = "poimandres-transparent"

[editor.cursor-shape]
insert = "bar"

[editor]
completion-timeout = 5

[editor.file-picker]
hidden = true

[keys.normal]
# Assumes git-link.py from collinmurch/scripts is available in $env.PATH
"space" = { "g" = { "l" = ":pipe-to git-link.py %{buffer_name} %{cursor_line}" } }
