[language-server.gopls]
config = { "buildFlags" = ["-tags=integrationtest,integration,manual"]}

[language-server.yaml-language-server]
config = { "yaml" = { "customTags" = [ "!reference sequence" ]}}
